"""Term-centric sub-chunking for precision retrieval.

Inspired by the term-centric functionality summarisation stage of RepoLens
(Wang et al., arXiv:2509.21427).

The problem with whole-function chunks
---------------------------------------
A standard AST chunker produces one vector embedding per function/class.
A 200-line function that handles authentication, rate-limiting, and session
management gets embedded as a single undifferentiated blob.  When a user
asks "how does rate limiting work?", the retriever must return the whole
function — wasting token budget and adding noise.

The term-centric solution
--------------------------
For each (symbol, term) pair, ask the LLM: "Describe only the logic in
this function that is directly related to ``rate limiting``."  This produces
a narrow, focused summary that embeds much more precisely.  Multiple
TermChunks are generated per function — one per relevant term — so the
retriever can pinpoint exactly which conceptual slice it needs.

TermChunks are **additions** to the index, not replacements.  Whole-function
chunks are still indexed; TermChunks give the retriever an extra, more
precise representation for the same code.

Usage::

    from code_indexer.llm import make_llm_client
    from code_indexer.graph.term_chunker import TermChunkExtractor
    from code_indexer.graph.term_enricher import TermEnricher, TermKnowledgeBase

    llm = make_llm_client(settings.llm)
    enricher = TermEnricher(llm)
    extractor = TermChunkExtractor(llm)

    kb = TermKnowledgeBase()
    for sym, source_text in symbols_with_source:
        terms = enricher.enrich_symbol(sym, source_text)
        chunks = extractor.extract(sym, source_text, terms)
        for chunk in chunks:
            kb.add_term(chunk.term, sym, summary=chunk.summary)
            # Also embed chunk.to_embedding_text() into your vector store
"""

from __future__ import annotations

import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from typing import TYPE_CHECKING

from code_indexer.graph.models import SymbolNode
from code_indexer.graph.term_enricher import EnrichedTerm

if TYPE_CHECKING:
    from code_indexer.llm.base import BaseLLMClient

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# TermChunk data model
# ---------------------------------------------------------------------------


@dataclass
class TermChunk:
    """A focused summary of one term's role within a specific symbol.

    Unlike a whole-function chunk, a ``TermChunk`` describes **only the
    logic within the symbol that is directly relevant to ``term``**.  This
    produces narrower, more precise retrieval units that avoid the
    "retrieve a huge function because it contains the keyword" problem.

    Attributes
    ----------
    symbol:
        The symbol (function/class/method) that this chunk is derived from.
    term:
        The enriched term that this chunk focuses on.
    summary:
        One-to-two sentence description of how the term's concept is used
        within ``symbol``.  Generated by :class:`TermChunkExtractor`.
    """

    symbol: SymbolNode
    term: EnrichedTerm
    summary: str

    # ------------------------------------------------------------------
    # Rendering helpers
    # ------------------------------------------------------------------

    def to_embedding_text(self) -> str:
        """Build the text string sent to the embedding model.

        Combines the term's enriched definition with the term-centric
        summary so the resulting vector captures both the concept's
        intrinsic meaning and its specific usage in the symbol.

        Example output::

            Term: HTTP request
            Definition: Incoming network message with headers and optional body.
            In verify_token (src/auth/jwt.py:42): validates the Bearer token
            extracted from the Authorization header of each HTTP request.
        """
        return (
            f"Term: {self.term.expanded_name}\n"
            f"Definition: {self.term.definition}\n"
            f"In {self.symbol.name} "
            f"({self.symbol.file_path}:{self.symbol.start_line}): "
            f"{self.summary}"
        )

    def to_prompt_line(self) -> str:
        """One-line representation for prompt injection."""
        return (
            f"  [{self.symbol.kind.value}] {self.symbol.qualified_name}"
            f"  re: {self.term.expanded_name} — {self.summary}"
        )

    def to_concern_text(self) -> str:
        """Compact representation used by :class:`ConcernClusterer`."""
        return (
            f"{self.symbol.name} ({self.symbol.file_path})"
            f" | {self.term.expanded_name}: {self.summary}"
        )


# ---------------------------------------------------------------------------
# TermChunkExtractor
# ---------------------------------------------------------------------------


class TermChunkExtractor:
    """Generate term-centric sub-chunks for a symbol using an LLM.

    For each term associated with a symbol, this class asks the LLM to
    summarise only the logic within that symbol that is relevant to the
    term.  If the symbol is unrelated to the term, the LLM is instructed
    to reply ``NOT_RELATED`` and the pair is skipped.

    The resulting :class:`TermChunk` objects should be:

    1. Embedded with :meth:`TermChunk.to_embedding_text` and stored in the
       vector index alongside whole-function chunks.
    2. Passed to :class:`~code_indexer.graph.term_enricher.TermKnowledgeBase`
       via :meth:`~code_indexer.graph.term_enricher.TermKnowledgeBase.add_term`
       to build the offline knowledge base.

    Parameters
    ----------
    llm:
        LLM client for generating summaries.  A cheap model like
        ``gpt-4o-mini`` is recommended — the prompt is short and the
        summaries are brief.
    """

    _SUMMARISE_PROMPT = (
        "Below is a code {kind} named `{name}` from `{file_path}`:\n\n"
        "```\n{source_text}\n```\n\n"
        "In 1–2 sentences, describe ONLY the logic in this {kind} that "
        "directly involves `{term_name}` ({term_definition}).\n"
        "Ignore all unrelated logic.\n"
        "If this {kind} has NO meaningful relationship with `{term_name}`, "
        "reply with exactly: NOT_RELATED\n\n"
        "Reply with only the 1–2 sentence description or NOT_RELATED."
    )

    def __init__(self, llm: "BaseLLMClient") -> None:
        self._llm = llm

    def extract(
        self,
        symbol: SymbolNode,
        source_text: str,
        terms: list[EnrichedTerm],
        *,
        max_tokens_per_summary: int = 80,
        source_text_limit: int = 1000,
    ) -> list[TermChunk]:
        """Generate one :class:`TermChunk` per term that is relevant to ``symbol``.

        Parameters
        ----------
        symbol:
            The symbol to analyse.
        source_text:
            Raw source code of the symbol.  Truncated to
            ``source_text_limit`` characters before being sent to the LLM.
        terms:
            Candidate terms to test for relevance within this symbol.
        max_tokens_per_summary:
            Maximum LLM output tokens per summary call (default ``80``).
        source_text_limit:
            Maximum characters of source text included in each prompt
            (default ``1000``).  Longer functions are truncated.

        Returns
        -------
        list[TermChunk]
            One chunk per relevant (symbol, term) pair.  Empty if no
            terms are relevant or all LLM calls fail.
        """
        chunks: list[TermChunk] = []
        truncated_src = source_text[:source_text_limit]

        for term in terms:
            try:
                chunk = self._summarise_one(
                    symbol,
                    truncated_src,
                    term,
                    max_tokens=max_tokens_per_summary,
                )
                if chunk is not None:
                    chunks.append(chunk)
            except Exception:  # noqa: BLE001
                logger.debug(
                    "TermChunkExtractor: failed for %s + term %r",
                    symbol.qualified_name,
                    term.expanded_name,
                )
        return chunks

    def extract_all(
        self,
        symbol_source_terms: list[tuple[SymbolNode, str, list[EnrichedTerm]]],
        *,
        concurrency: int = 20,
    ) -> list[TermChunk]:
        """Extract term chunks for multiple symbols concurrently.

        Runs :meth:`extract` for every ``(symbol, source_text, terms)``
        triple in parallel.  Because each call makes one LLM request per
        term, parallelising across symbols gives the same throughput
        improvement as :meth:`~TermEnricher.enrich_all`.

        Parameters
        ----------
        symbol_source_terms:
            List of ``(SymbolNode, source_text, terms)`` triples.
        concurrency:
            Maximum number of symbols to process simultaneously.
            Default ``20`` — reduce to ``1`` for local Ollama.

        Returns
        -------
        list[TermChunk]
            All generated chunks from every symbol, in completion order.
            Failed workers are skipped and logged at DEBUG level.
        """
        all_chunks: list[TermChunk] = []

        def _worker(
            sym: SymbolNode, src: str, terms: list[EnrichedTerm]
        ) -> list[TermChunk]:
            return self.extract(sym, src, terms)

        with ThreadPoolExecutor(max_workers=concurrency) as executor:
            futures = [
                executor.submit(_worker, sym, src, terms)
                for sym, src, terms in symbol_source_terms
            ]
            for future in as_completed(futures):
                try:
                    all_chunks.extend(future.result())
                except Exception:  # noqa: BLE001
                    logger.debug("extract_all: worker failed")

        return all_chunks

    def _summarise_one(
        self,
        symbol: SymbolNode,
        source_text: str,
        term: EnrichedTerm,
        *,
        max_tokens: int,
    ) -> TermChunk | None:
        """Ask the LLM to summarise one (symbol, term) pair.

        Returns ``None`` if the symbol is not related to the term.
        """
        prompt = self._SUMMARISE_PROMPT.format(
            kind=symbol.kind.value,
            name=symbol.name,
            file_path=symbol.file_path,
            source_text=source_text,
            term_name=term.expanded_name,
            term_definition=term.definition,
        )
        summary = self._llm.complete(prompt, max_tokens=max_tokens).strip()

        if not summary or "NOT_RELATED" in summary:
            return None

        return TermChunk(symbol=symbol, term=term, summary=summary)
