"""Term enrichment pipeline: expand abbreviations and generate definitions.

Inspired by the offline knowledge-extraction stage of RepoLens
(Wang et al., arXiv:2509.21427).  The core insight is that code identifiers
like ``req``, ``tx``, or ``svc`` are opaque to embedding models trained on
natural language.  By expanding them to ``HTTP request``, ``database
transaction``, and ``email service`` and generating short natural-language
definitions, we close the vocabulary gap between user queries and the code.

Pipeline (per symbol)
---------------------
1. Extract raw noun tokens from the symbol's name and parent name.
2. For each token, ask the LLM to expand it to its full English form
   (e.g. ``repo`` → ``user repository``).
3. Ask the LLM for a one-sentence definition of the expanded term.
4. Store as an :class:`EnrichedTerm` in the :class:`TermKnowledgeBase`.

The knowledge base is built **once offline** (amortised across all queries)
and serialises to JSON for persistence between process restarts.

Usage::

    from code_indexer.llm import make_llm_client
    from code_indexer.graph.term_enricher import TermEnricher, TermKnowledgeBase
    from code_indexer.core.config import get_settings

    settings = get_settings()
    llm = make_llm_client(settings.llm)
    enricher = TermEnricher(llm)

    kb = TermKnowledgeBase()
    for sym, source_text in symbols_with_source:
        terms = enricher.enrich_symbol(sym, source_text)
        for term in terms:
            kb.add_term(term, sym, summary="<generated by TermChunkExtractor>")

    kb.save(".term_kb.json")
"""

from __future__ import annotations

import json
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from code_indexer.graph.models import SymbolNode
from code_indexer.graph.term_utils import extract_noun_tokens, keywords_from_query, split_identifier

if TYPE_CHECKING:
    from code_indexer.llm.base import BaseLLMClient

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class EnrichedTerm:
    """A code identifier enriched with its full English form and definition.

    Attributes
    ----------
    raw_name:
        The original identifier token as it appears in source code
        (e.g. ``"req"``, ``"repo"``, ``"txManager"``).
    expanded_name:
        Full English form inferred by the LLM
        (e.g. ``"HTTP request"``, ``"user repository"``).
    definition:
        One-sentence natural-language definition of the concept,
        independent of how it is used in a specific function.
    noun_tokens:
        Tokens obtained by splitting ``expanded_name`` — used for
        keyword matching in :meth:`TermKnowledgeBase.search`.
    """

    raw_name: str
    expanded_name: str
    definition: str
    noun_tokens: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.noun_tokens:
            self.noun_tokens = split_identifier(self.expanded_name)

    def to_embedding_prefix(self) -> str:
        """Short text prepended to embedding inputs to enrich the vector."""
        return f"{self.expanded_name}: {self.definition}"


@dataclass
class TermFunctionality:
    """A term-centric summary of one symbol's role with respect to a term.

    Records which symbol uses the term and a short description of *how*
    the symbol uses it — independent of the symbol's overall purpose.

    Attributes
    ----------
    file_path:
        Repo-relative path of the file containing the symbol.
    symbol_name:
        Short name of the symbol (e.g. ``"verify_token"``).
    qualified_name:
        Full dotted name (e.g. ``"auth.jwt.JWTHandler.verify_token"``).
    summary:
        One-to-two sentence description of the term's role in the symbol.
        Generated by :class:`~code_indexer.graph.term_chunker.TermChunkExtractor`.
    """

    file_path: str
    symbol_name: str
    qualified_name: str
    summary: str


@dataclass
class TermEntry:
    """All knowledge about one enriched term across the codebase.

    Attributes
    ----------
    term:
        The enriched term (expanded name + definition).
    functionalities:
        List of per-symbol summaries — one per function/class that uses
        the term in a meaningful way.
    """

    term: EnrichedTerm
    functionalities: list[TermFunctionality] = field(default_factory=list)

    def to_prompt_text(self, max_functionalities: int = 5) -> str:
        """Render as a block suitable for injecting into an LLM prompt."""
        lines: list[str] = [
            f"Term: {self.term.expanded_name}",
            f"Definition: {self.term.definition}",
        ]
        if self.functionalities:
            lines.append("Usages:")
            for fn in self.functionalities[:max_functionalities]:
                lines.append(f"  • {fn.symbol_name} ({fn.file_path}): {fn.summary}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Knowledge base
# ---------------------------------------------------------------------------


class TermKnowledgeBase:
    """In-memory store of enriched terms and their per-symbol summaries.

    Built offline during indexing, then queried online for each user request.
    Supports JSON serialisation for persistence between process restarts.

    The key is ``expanded_name`` (lower-cased) so that terms with the same
    meaning but different raw identifiers (``repo``, ``repository``) collapse
    into a single entry.
    """

    def __init__(self) -> None:
        # expanded_name.lower() → TermEntry
        self._entries: dict[str, TermEntry] = {}

    # ------------------------------------------------------------------
    # Write API
    # ------------------------------------------------------------------

    def add_term(
        self,
        term: EnrichedTerm,
        symbol: SymbolNode,
        summary: str,
    ) -> None:
        """Add or update a term entry with a new per-symbol functionality.

        Parameters
        ----------
        term:
            The enriched term.
        symbol:
            The symbol that uses the term.
        summary:
            Term-centric summary for this (term, symbol) pair.
        """
        key = term.expanded_name.lower()
        fn = TermFunctionality(
            file_path=symbol.file_path,
            symbol_name=symbol.name,
            qualified_name=symbol.qualified_name,
            summary=summary,
        )
        if key in self._entries:
            self._entries[key].functionalities.append(fn)
        else:
            self._entries[key] = TermEntry(term=term, functionalities=[fn])

    # ------------------------------------------------------------------
    # Read API
    # ------------------------------------------------------------------

    def get(self, expanded_name: str) -> TermEntry | None:
        """Look up a term by its expanded name (case-insensitive)."""
        return self._entries.get(expanded_name.lower())

    def search(self, keywords: list[str]) -> list[TermEntry]:
        """Return entries whose tokens overlap with ``keywords``.

        Entries are sorted by descending overlap count so the most
        relevant terms appear first.

        Parameters
        ----------
        keywords:
            List of lowercase keyword tokens (typically produced by
            :func:`~code_indexer.graph.term_utils.keywords_from_query`).

        Returns
        -------
        list[TermEntry]
            Matching entries, best-overlap first.
        """
        kw_set = {k.lower() for k in keywords}
        scored: list[tuple[int, TermEntry]] = []
        for entry in self._entries.values():
            token_set = set(entry.term.noun_tokens) | {entry.term.expanded_name.lower()}
            overlap = len(kw_set & token_set)
            if overlap > 0:
                scored.append((overlap, entry))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [e for _, e in scored]

    def search_for_query(self, query: str) -> list[TermEntry]:
        """Convenience wrapper: extract keywords from a query then search."""
        return self.search(keywords_from_query(query))

    def all_entries(self) -> list[TermEntry]:
        return list(self._entries.values())

    def __len__(self) -> int:
        return len(self._entries)

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def save(self, path: str | Path) -> None:
        """Serialise the knowledge base to a JSON file.

        Parameters
        ----------
        path:
            Destination file path.  Parent directories must exist.
        """
        data = []
        for entry in self._entries.values():
            data.append(
                {
                    "term": {
                        "raw_name": entry.term.raw_name,
                        "expanded_name": entry.term.expanded_name,
                        "definition": entry.term.definition,
                        "noun_tokens": entry.term.noun_tokens,
                    },
                    "functionalities": [
                        {
                            "file_path": fn.file_path,
                            "symbol_name": fn.symbol_name,
                            "qualified_name": fn.qualified_name,
                            "summary": fn.summary,
                        }
                        for fn in entry.functionalities
                    ],
                }
            )
        Path(path).write_text(json.dumps(data, indent=2), encoding="utf-8")
        logger.info("TermKnowledgeBase: saved %d terms to %s", len(self), path)

    @classmethod
    def load(cls, path: str | Path) -> "TermKnowledgeBase":
        """Deserialise a knowledge base from a JSON file.

        Parameters
        ----------
        path:
            Path to a file previously written by :meth:`save`.

        Returns
        -------
        TermKnowledgeBase
            Populated knowledge base.
        """
        kb = cls()
        raw = json.loads(Path(path).read_text(encoding="utf-8"))
        for item in raw:
            term = EnrichedTerm(**item["term"])
            for fn_data in item.get("functionalities", []):
                fn = TermFunctionality(**fn_data)
                key = term.expanded_name.lower()
                if key in kb._entries:
                    kb._entries[key].functionalities.append(fn)
                else:
                    kb._entries[key] = TermEntry(term=term, functionalities=[fn])
        logger.info("TermKnowledgeBase: loaded %d terms from %s", len(kb), path)
        return kb


# ---------------------------------------------------------------------------
# Enricher
# ---------------------------------------------------------------------------


class TermEnricher:
    """Enrich code identifiers with full English names and definitions.

    Uses a cheap LLM (``gpt-4o-mini`` by default) to:

    1. **Expand** abbreviated tokens: ``req`` → ``HTTP request``.
    2. **Define** expanded terms: one-sentence intrinsic definition
       independent of how the term is used in any particular function.

    The enrichment is context-aware: the full symbol source text is
    passed to the LLM so it can infer what ``req`` means from the
    surrounding HTTP handler code vs. a database layer.

    Cost note
    ---------
    The LLM calls are per-token, not per-query.  Because the knowledge
    base is built once and persisted to JSON, the LLM cost is amortised
    across all queries for a given repository.  Using ``gpt-4o-mini``
    with a 200-symbol repo and 3 tokens/symbol averages ~600 calls,
    costing roughly $0.05–$0.10 total.
    """

    # Kept intentionally terse to minimise tokens.
    _EXPAND_PROMPT = (
        "Code context:\n\n{source_text}\n\n"
        "The identifier `{raw_name}` appears in the code above.\n"
        "Expand it to its full English noun phrase (2–5 words). "
        "Reply with ONLY the expanded phrase, no punctuation, no explanation."
    )

    _DEFINE_PROMPT = (
        "Define the software concept `{expanded_name}` in one sentence (max 20 words). "
        "Describe what it IS in general — not how it is used in any specific codebase. "
        "Do not start with 'A' or 'The'. Reply with only the sentence, no quotes."
    )

    def __init__(self, llm: "BaseLLMClient") -> None:
        self._llm = llm

    def enrich_symbol(
        self,
        symbol: SymbolNode,
        source_text: str,
        *,
        max_terms: int = 5,
    ) -> list[EnrichedTerm]:
        """Extract and enrich noun tokens from a symbol.

        Parameters
        ----------
        symbol:
            The symbol to process.
        source_text:
            Raw source text of the symbol (function/class body).
            Truncated to 800 characters before being sent to the LLM.
        max_terms:
            Maximum number of tokens to enrich (default ``5``).

        Returns
        -------
        list[EnrichedTerm]
            Enriched terms.  Empty if the LLM is unavailable or all
            tokens fail to enrich.
        """
        # Collect candidate tokens from name + parent name
        idents = [symbol.name]
        if symbol.parent_name:
            idents.append(symbol.parent_name)

        raw_tokens = extract_noun_tokens(idents, remove_stop_words=True)

        enriched: list[EnrichedTerm] = []
        truncated_src = source_text[:800]

        for token in raw_tokens[:max_terms]:
            try:
                term = self._enrich_one(token, truncated_src)
                if term:
                    enriched.append(term)
            except Exception:  # noqa: BLE001
                logger.debug(
                    "TermEnricher: failed to enrich token %r in %s",
                    token,
                    symbol.qualified_name,
                )
        return enriched

    def enrich_all(
        self,
        symbols_with_source: list[tuple[SymbolNode, str]],
        *,
        concurrency: int = 20,
        max_terms: int = 5,
    ) -> dict[str, list[EnrichedTerm]]:
        """Enrich multiple symbols concurrently using a thread pool.

        Runs :meth:`enrich_symbol` for every (symbol, source) pair in
        parallel.  Each worker makes 2 × ``max_terms`` LLM calls (expand +
        define per token), so with ``concurrency=20`` those calls are
        issued in batches of up to 20 at a time instead of sequentially.

        Parameters
        ----------
        symbols_with_source:
            List of ``(SymbolNode, source_text)`` pairs to process.
        concurrency:
            Maximum number of symbols to enrich simultaneously.
            Match this to your API rate limit tier; default ``20`` is safe
            for OpenAI Tier-1.  Reduce to ``1`` for local Ollama.
        max_terms:
            Forwarded to :meth:`enrich_symbol`.

        Returns
        -------
        dict[str, list[EnrichedTerm]]
            Mapping of ``symbol.id`` → enriched terms.  Symbols that fail
            are mapped to an empty list rather than raising.
        """
        results: dict[str, list[EnrichedTerm]] = {}

        def _worker(sym: SymbolNode, src: str) -> tuple[str, list[EnrichedTerm]]:
            return sym.id, self.enrich_symbol(sym, src, max_terms=max_terms)

        with ThreadPoolExecutor(max_workers=concurrency) as executor:
            future_to_id = {
                executor.submit(_worker, sym, src): sym.id
                for sym, src in symbols_with_source
            }
            for future in as_completed(future_to_id):
                sym_id = future_to_id[future]
                try:
                    _, terms = future.result()
                    results[sym_id] = terms
                except Exception:  # noqa: BLE001
                    logger.debug("enrich_all: worker failed for symbol %s", sym_id)
                    results[sym_id] = []

        return results

    def _enrich_one(self, raw_name: str, source_text: str) -> EnrichedTerm | None:
        """Run LLM calls for a single token: expand then define."""
        # Step 1 — expand abbreviation
        expand_prompt = self._EXPAND_PROMPT.format(
            source_text=source_text, raw_name=raw_name
        )
        expanded = self._llm.complete(expand_prompt, max_tokens=16).strip()
        if not expanded:
            expanded = raw_name.replace("_", " ")

        # Step 2 — generate definition
        define_prompt = self._DEFINE_PROMPT.format(expanded_name=expanded)
        definition = self._llm.complete(define_prompt, max_tokens=40).strip()
        if not definition:
            definition = f"Code concept related to {expanded}"

        return EnrichedTerm(
            raw_name=raw_name,
            expanded_name=expanded,
            definition=definition,
        )
